### ISSUE TITLE
Feedback session 2 [meta]

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting#163]
Small

- [x] #159 - reduce vertical spacing

- [x] https://github.com/openclimatefix/nowcasting/issues/160 - OCF hyperlink
- [x] https://github.com/openclimatefix/nowcasting/issues/161 - headline figure 1.d.p
- [x] https://github.com/openclimatefix/nowcasting/issues/169 -set MW (not %) to default 

Medium
- [x] https://github.com/openclimatefix/nowcasting/issues/171
- [x] https://github.com/openclimatefix/nowcasting/issues/172
- [x] https://github.com/openclimatefix/nowcasting/issues/173
- [ ] https://github.com/openclimatefix/nowcasting/issues/175
- [x] https://github.com/openclimatefix/nowcasting/issues/170

R&D
- [x] https://github.com/openclimatefix/nowcasting/issues/174
- [x] https://github.com/openclimatefix/nowcasting/issues/162 - rainbow colours

**Comment by peterdudfield** [comment]
Ill close this for the moment
