### ISSUE TITLE
Build a minimal UI

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting#4]
Create simple front end for Nowcasting

## Detailed Description
- Front end should pull data from API service
- Display should be in a map
- Try React technology
- terraform to deploy on docker file on elasticbeanstalk

## Tasks

- [x] Create basic app wireframe
- [x] Add login with Auth0 (OCF domain only)
- [x] Deploy via vercel
- [x] Add map component
- [x] Fetch data locally
- [x] Fetch data from dev endpoint
- [x] Display data

**Comment by peterdudfield** [comment]
- Should this UI be in a separate repo? 
- Is there a docker file for this? 
- Is the docker file on dockerhub?
- Would be great to add to [local stack](https://github.com/openclimatefix/nowcasting_infrastructure/tree/main/local-stack)

**Comment by flowirtz** [comment]
> Should this UI be in a separate repo?

No, I don't think so. I really enjoy everything being in a single place. I'd even advocate for moving everything production service related into a single repository - monorepos are nice! We could eg start autogenerating the frontend types from the [nowcasting_datamodel](https://github.com/openclimatefix/nowcasting_datamodel) and reuse them everywhere.

**Comment by peterdudfield** [comment]
> > Should this UI be in a separate repo?
> 
> No, I don't think so. I really enjoy everything being in a single place. I'd even advocate for moving everything production service related into a single repository - monorepos are nice! We could eg start autogenerating the frontend types from the [nowcasting_datamodel](https://github.com/openclimatefix/nowcasting_datamodel) and reuse them everywhere.

that would involve moving
- nowcasting_datamodel
- nowcasting_infrastructure
- nowcasting_api
- nowcasting_forecast
- nowcasting_dataset

I would rather keep these python repos separate at the moment. There will be a few more components and its bery easy to version them if they are seperate.

perhaps a good comprise is to keep all front end projects here. 


Nethertheless, is there an easy to access dockerfile for this front end?
