### ISSUE TITLE
[Meta] MVP User Interface v0.2

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting#9]
- [x] Map of GB showing each GSP
- [x] GSPs are coloured in respective quanta (heatmap, `d3.scaleQuantize`)
- [x] Time Selector/Slider at the bottom to select forecast horizon
- [x] Display additional information per GSP (name, capacity?, etc.)

- [x] Option to view National Forecast

**Stretch Goals**
- [ ] Dockerise and add to [our local stack](https://github.com/openclimatefix/nowcasting_infrastructure/tree/main/local-stack)

**Comment by peterdudfield** [comment]
Nice use of '[Meta]'

**Comment by peterdudfield** [comment]
amazing - well done @flowirtz - im looking froward to seeing it
